# Generated by Django 3.0 on 2019-12-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='paradism',
            new_name='paradigm',
        ),
    ]
